### ISSUE TITLE
Food pallet can appear on Tail prefab

### ISSUE THREAD

**Issue by KKucharczyk** [KKucharczyk/Snake#33]

**Comment by Marrkix** [comment]
Well, I don't think that this is actually a bug, that's how I assumed it to work. Tail is the part of body without boxcollider, so it's not being detected by neither Physics2D.Raycast nor OnTriggerEnter. So yeah, you can also move snake's head on it without dying. It's here only for graphical matters. We could ofcourse change the last body part to have tail sprite, but then what to do at start, when snake doesn't have any of it? Additional head sprites only for few first seconds? I think this way now is pretty good, we can maybe just shorten its sprite a little, so it would be more intuitive that it's non collidable, and lower its render priority, to make sure it will be displayed below food or head.

**Comment by KKucharczyk** [comment]
I am down for changing sprite size. Easy and not require to actually dismantle the board controller.
